### PR TITLE
Added cmake file to make building on multiple OSes and IDEs easier

### PR DESCRIPTION
**Pull request by SeleDreams**
Since the project only had Makefiles and visual studio solutions, I felt like a CMakeLists would be useful as they are a unified way to build C/C++ programs on any OS and any IDE. So I made one, I might also make some for the example projects but at the moment I only made one for WORLD itself. It at the moment builds WORLD as a shared library.

### CODE REVIEW

**Comment by r9y9** [comment]
Hello there.  FWIW, here goes my attempt to add CMake support for WORLD: https://github.com/r9y9/World-cmake. I've been using it over a year and had no problem with it so far.

I personally agree that cmake is more convenient than pure makefiles and can be used for various platforms (Windows, Mac OS X, Linux, etc). Although we can do with by forking the repository, it would be great if the official repo supports cmake.

**Comment by mmorise** [comment]
Thank you for your request and comment.
I checked it and think that it is reasonable to add the cmake file, as you pointed out.

On the other hand, there are two ideas (from @SeleDreams and @r9r9 ), and I waver between them. The first idea seems to be more straightforward because the second idea requires to add other files. If the second idea is better than the first idea, I'd like to accept it as another PR.

**Comment by SeleDreams** [comment]
I guess either would work

My solution was more meant to allow to easily build on any platform while keeping the maintaining cost low (to avoid having to modify it too much when changing stuff)

so basically mine is really the "simple and easy option" now for something that is more advanced I guess the second works as well.

**Comment by mmorise** [comment]
Thank you for your comment.

I am going to accept your request soon.

**Pull request merged**
