### PR TITLE
Exposing C interface in the library, instead of C++ interface

### PR DESCRIPTION
**Pull request by giuliopaci**
This pull request is the first attempt to expose a C interface instead of C++.
I introduced a defs.h file, based on defs.h and visibility.h files shipped with speect. This file provides useful definitions that can be used to create portable libraries. Right now I have used only the *C_DECLS macros, but *API and *LOCAL are also very useful, especially if one wants to create a (portable) dynamic library instead of a static one.

I had to redefine MyMin and MyMax, otherwise there would be a clash in a C interface.

I added *C_DECLS in the headers files, so that the compiler knows that the symbols are C symbols and not C++ symbols. This is enough to expose a C interface.

The current situation after the pull request is that a C++ compiler is still needed to compile the library, but the headers and the library can be used in a plain C program.

A C++ linker is still needed to link the C program, as new and delete symbols should be linked in the program.

If this pull request will be accepted, my plan is to replace new/delete with malloc/free, so that the library can be compiled with a plain C compiler and the C++ linker is not needed anymore.

### CODE REVIEW

**Comment by mmorise** [comment]
I think that these modifications are too massive.
WORLD project simply provides the functions in the signal processing, and I think that the advanced expansions should be carried out by each user.

I will accept the redefinition of the functions, but the names should follow the rules in other functions.
In this case, I propose the names (MyMaxInt(), MyMinInt(), MyMaxDouble() and MyMinDouble()).
In WORLD, I have avoid using macros in the functions.
It is enough to write the commands such as "extern "C" {" in each header file.
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
The defs.h has too many functions, but they are unfortunately not important in the signal processing.
I would like to provide the simple functions in WORLD's signal processing.

If you think that the modifications are crucial, I propose that you create another project as your original one.
These functions are helpful for developers sharing the same purpose.
Actually, I am considering the use of the smart pointer in the next release.
It is opposite compared with your plan, but the user around me hopes to use it.

Best regards,

**Comment by giuliopaci** [comment]
OK, I will rename the min/max functions according to your scheme (Mine was based on math.h functions).

If you really prefer to have ifdef in alla the public headers, and not in a central place, I will also replace the macros with explicit code.

Regarding the other macros in defs.h, I have to say that no single function is defined there and that the code is really useful if you have the goal "that the advanced expansions should be carried out by each user", as you will find them very convenient when you will decide to let your user compile a dynamic library, especially understand windows. They are meant to portably deal with differences in compilers behaviour with respect to libraries. E.g., in msvc alla the symbols are not exported by default, while gcc exports alla of them. With msvc, you have to declare in two different ways functions according to the fact that you are compiling them, or using them. This particularly means that you need to triplicate all the headers (one for static library/most of the platform compilation and usage, one for msvc DLL compilation and one for msvc DLL usage) or implement some mechanism like what is implemented in defs.h. But the code in defs.h has been used and tested extensively across several platforms. I want you to understand this, before dropping it. Then, as currently you are not providing a dynamic library, I will drop and eventually reintroduce it when and if you will want to let world be compiled as a proper dynamic library.

**Comment by giuliopaci** [comment]
I updated the pull request to cope with MyMin/MyMax changes you requested and made more clean.

I am waiting feedback about defs.h and *C_DECLS macros.

Please also have a look at commit 31efcad: it is an error to report success (0) on failures in programs.

From your previous comment I did not understand if commits 4868706 and bf5b1cf are welcome or not. If not, if we want C interface compatibility, the library should also provide a destruction method for the returned array, wrapping delete function.

**Comment by mmorise** [comment]
Sorry, I have several deadlines and don't have enough time to consider it.
I basically agree with you and think that a modification is necessary for compatibility.
A worry is that the new/delete and malloc/free in matlabfunctions.cpp are mixed.
Another idea is following.
Memory allocation is not carried out in wavread() in matlabfunctions.cpp.
The program is modified so that the memory is allocated in test.cpp by implementing new function for memory allocation such as GetSamplesForDIO().
// example
GetAudioInformation(argv[1], &x_length, &fs, &nbit); // This is a new function.
double *x = new double[x_length]; // malloc is also available.
wavread(argv[1], x);

In this case, I would like to implement the wave input/output functions as another file (audioio.cpp?) because they are not signal processing functions.
We can use other libraries for audio I/O.
If you wait for a few days, I will implement their functions.

In defs.h, I understand the effectiveness of the macros.
However, I will follow the Google C++ Style Guide in the future, and the use of Macro is unfavorable in this guide.
Since there are several topics in this pull request, will you fix other pull requests in C compatibility?
(At least, I think that a test script for C interface is also crucial.
However, such modification is too massive as one modification.)

**Comment by Sleepwalking** [comment]
> We can use other libraries for audio I/O.
> If you wait for a few days, I will implement their functions.

@mmorise Just to mention that I've extended your implementation of `wavread` & `wavwrite` [here](https://github.com/Sleepwalking/libllsm/blob/multiband-noise/external/matlabfunctions.c), which is used in Moresampler. Please feel free to use.

**Comment by giuliopaci** [comment]
Please, tell me what you want to keep from this pull request and what you want that I reserve for future pull requests, otherwise I cannot adapt this pull request.

Please, also note that Google C++ Style Guide suggest the use of macros for DLL: https://google.github.io/styleguide/cppguide.html#Windows_Code
I would avoid non-project specific macros names, because otherwise they are likely to cause troubles to people developing libraries on top of this library.

**Comment by mmorise** [comment]
Thank you for your suggestion.
I have overlooked this information.

I'd like to accept the following requests.
55f6307, 	2d9266b, 2bee2ff, dfba4b3, b9032f3, 856c51e, 234a8c8,
db7c0db, 57a5dd4, af8386c, 5e2bf76, 7b3e988, 335f2d3, and 31efcad.

In 4a4670c, there are several requirements.
(1) Please rename the file. defs.h is too short. macrodefinitions.h is one idea.
(2) Please use // instead of /* */.
(3) 
```c
#ifndef _WORLD_DEFS_H__
```
should be
```c
#ifndef WORLD_DEFS_H_
```
If possible, please check the modification by cpplint.py provided by Google.
If you permit me to modify the code after acceptance, I will merge the current request.

In 4868706, I will modify this function not to allocate memory.
If you are not hurry, please wait for the completion of the modification.
In bf5b1cf, I think this modification is not necessary because of modifying the wavread() function based on the comment in 4868706.

Best regards,

**Comment by giuliopaci** [comment]
I just dropped commits 4868706 and bf5b1cf.
I kept all the revisions you mentioned, plus one that I think you just forgot  (same changes applied to cheaptrick.h) and refreshed them, according to your requests.

In defs.h I also removed some references to speect and cmake, as they are not relevant in world.
I also removed a macro definition that was not relevant to a single library project.

**Comment by giuliopaci** [comment]
BTW: I just realized that you did not mention dae3e86. I hope that commit is fine.
It is a bad practice to have automatically generated binary files in a git repository.

**Comment by mmorise** [comment]
In dae3e86, your comment is reasonable, and I will accept this request.

I checked the code and detected several minor errors in the appearance.
(For example, at least two spaces is best between code and comments in macrodefinitions.h.
Since they are delicate modifications, I first merge the requests and then would like to revise these errors.)

Is it OK to go ahead?

**Comment by giuliopaci** [comment]
Sure. I can easily track (almost) whatever you do from git. :-)
The main exception being commits that affects several files, that may require so much extra work to proper handling them in complex environments, that I decided to have a commit policy of "one file per commit" and replace the notion of "all revisions should compile" with the notion "alla push should compile, if something intermediate deserves to be remembered as a compiling point, it probably deserves a tag".

**Pull request merged**
