### PR TITLE
Add ctest example and several improvements in makefile

### PR DESCRIPTION
**Pull request by giuliopaci**
As you wanted an example of C usage, I added C version of test.cpp.
I also fixed some issues with makefiles and tried to improve it in several ways.

### CODE REVIEW

**Comment by mmorise** [comment]
It seems a reasonable request.
Please give me a time to check it.

If there are no major problem in the request, I will merge it.
I might modify the appearance after acceptance.

**Comment by giuliopaci** [comment]
Perfect. :-)

**Comment by mmorise** [comment]
I checked your requirements. 
I basically agree with you but have two questions.

In ctest.c, do you permit the following code?
```
for (int i = 0; i < f0_length; ++i) {
```
A traditional C compiler disallows the above code.
Instead, the code should be
```
int i;
for (i = 0; i < f0_length; ++i) {
```
I think that the latter code is preferred for the perfect C interface.
Could you show your view?

makefile seems to contain two errors.
In 41, "mkdir -p $(OUT_DIR)/objs/test" is "mkdir -p $(OUT_DIR)/objs"
In 45, "mkdir -p $(OUT_DIR)/objs" is "mkdir -p $(OUT_DIR)/objs/test"
If the folders /objs and /objs/test do not exist, we cannot compile the project.

Best regards,

**Comment by giuliopaci** [comment]
If you want portability, you are right. The form that I used require a modern C compiler (I guess C99 should be enough to support it). Actually, for portability, all the vatiables should be declared at the beginning of the function, before anything else happens.
I am not aware of a compiler that will fail on the current code that will not fail on the other code if "int i" does not appear at the beginning of the function.

I will fix the issues as soon as I get a PC. :-)

**Comment by giuliopaci** [comment]
I just updated the pull request.

Regarding ctest.c, my opinion is to leave it as it is, or modify test.cpp accordingly:
PROS:
- I generated ctest.c automatically from test.cpp without any manual editing;
- it is exactly the same example of test.cpp, so none will think there are differences in those binaries and there will be any incompatibilities due to implementation details;
CONS:
- it may fail to compile on ancient compilers;
- it will fail to compile if some flags are used to enforce the usage of a specific standard;
- I consider bad practice to declare variables on the go (i.e.: not at the beginning of a block), especially if their scope is ambiguos, like in this case.

**Comment by mmorise** [comment]
I see. I propose another modification in makefile.
```
CFLAGS = -O1 -g -Wall -fPIC
CXXFLAGS = $(CFLAGS)
```
is modified to
```
CXXFLAGS = -O1 -g -Wall -fPIC
CFLAGS = $(CXXFLAGS) -std=c99 
```
If the compiler is explicitly assigned, we will avoid the unnecessary trouble.
It is also the statement that we don't support ancient compilers.

**Comment by giuliopaci** [comment]
I fixed an error in makefile and made modification similar, in spirit, to what you asked:
instead of adding the flag to CFLAGS, I defined C99 variable and added the flag to it. I think it is the most flexible approach.

**Comment by mmorise** [comment]
I hate to ask you to do this, but I need you to update your request based on the latest version.
(I have updated WORLD yesterday. I think that your makefile would be able to be used in this version.
If you can automatically generate ctest.c from test.cpp, I believe that it is not a difficult task.).

**Comment by giuliopaci** [comment]
I just refreshed the pull request and updated ctest.c.
Now ctest.c is generated in a semi-automatic way, as it is tricky to convert the use of anonymous namespaces into static linkage without implementing a proper parser.

Do you think it would be possible to use static linkage in World instead of (or in addition to) anonymous namespaces? I know this is not your goal, but this will let me to have a working plain C version of World using just a few regexp.

**Comment by mmorise** [comment]
Thank you for updating files. After this comment, I will accept the pull request.
Since this thread will close, please create another thread if needed.

I prefer to use anonymous namespaces, but I don't think that it is essential because the Google Style Guide does not disallow static linkage.
I guess that your purpose is to automatically generate *.c from *.cpp.
My concern is that D4C uses std::sort().
Automatic conversion is difficult. Or do you have an idea?

**Comment by giuliopaci** [comment]
Yes, that is my goal.
For std:sort I am replacing with a custom double compare function and qsort. However I am not getting bit-to-bit identical output from the converted code. So, yes, this is tricky. :-)

**Pull request merged**
