### PR TITLE
Add makefile and fix a memory overflow bug

### PR DESCRIPTION
**Pull request by Sleepwalking**
```
$ valgrind ./build/test test/vaiueo2d.wav out.wav 2
==22024== Memcheck, a memory error detector
==22024== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==22024== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==22024== Command: ./build/test test/vaiueo2d.wav out.wav 2
==22024== 
File information
Sampling : 22050 Hz 16 Bit
Length 17500 [sample]
Length 0.793651 [sec]

Analysis
DIO: 737 [msec]
StoneMask: 738 [msec]
CheapTrick: 750 [msec]
D4C: 1792 [msec]

Synthesis
==22024== Invalid read of size 8
==22024==    at 0x40FBA1: Synthesis(double*, int, double**, double**, int, double, int, int, double*) (synthesis.cpp:191)
==22024==    by 0x401554: main (test.cpp:183)
==22024==  Address 0x5ed39e8 is 0 bytes after a block of size 1,272 alloc'd
==22024==    at 0x4C2B800: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x400ED4: main (test.cpp:213)
==22024== 
==22024== Invalid read of size 8
==22024==    at 0x40FC04: Synthesis(double*, int, double**, double**, int, double, int, int, double*) (synthesis.cpp:195)
==22024==    by 0x401554: main (test.cpp:183)
==22024==  Address 0x5ed39e8 is 0 bytes after a block of size 1,272 alloc'd
==22024==    at 0x4C2B800: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x400ED4: main (test.cpp:213)
==22024== 
==22024== Invalid read of size 8
==22024==    at 0x40FC10: Synthesis(double*, int, double**, double**, int, double, int, int, double*) (synthesis.cpp:195)
==22024==    by 0x401554: main (test.cpp:183)
==22024==  Address 0x5ed39e8 is 0 bytes after a block of size 1,272 alloc'd
==22024==    at 0x4C2B800: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x400ED4: main (test.cpp:213)
==22024== 
WORLD: 1590 [msec]
complete.
==22024== 
==22024== HEAP SUMMARY:
==22024==     in use at exit: 72,709 bytes in 2 blocks
==22024==   total heap usage: 14,574 allocs, 14,572 frees, 118,718,541 bytes allocated
==22024== 
==22024== LEAK SUMMARY:
==22024==    definitely lost: 0 bytes in 0 blocks
==22024==    indirectly lost: 0 bytes in 0 blocks
==22024==      possibly lost: 0 bytes in 0 blocks
==22024==    still reachable: 72,709 bytes in 2 blocks
==22024==         suppressed: 0 bytes in 0 blocks
==22024== Rerun with --leak-check=full to see details of leaked memory
==22024== 
==22024== For counts of detected and suppressed errors, rerun with: -v
==22024== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```

### CODE REVIEW

**Comment by mmorise** [comment]
(1) stonemask.cpp
Your suggestion is correct. I'll accept your request.

(2) makeflie
There is already a makefile in platform/linux/
I'd like to use your idea, but I have no idea on the path that this file should be put.
Do you hope that makefile is set to the top of project?
If no, I will revise the platform/linux/Makefile.linux based on your idea.

(3) others
in .gitignore, I will use your idea, but I will also add an additional file types.
Now I'm investigating the details of .gitignore.

**Comment by Sleepwalking** [comment]
Welcome to Github:)

Oh sorry I didn't noticed there's already a makefile under `platform/`.
Conventionally we look for makefile under the top directory or `src/`.

The problem with the one under `platform/` is: source's (`*.cpp`) dependency on headers (`*.h`) are neglected, which means after you modify a header file and re-make, nothing would happen.

We can explicitly write down their dependencies:
```makefile
$(OUT_DIR)/cheaptrick.o : src/cheaptrick.h src/common.h src/constantnumbers.h src/matlabfunctions.h
$(OUT_DIR)/common.o : src/common.h src/constantnumbers.h src/matlabfunctions.h
$(OUT_DIR)/d4c.o : src/d4c.h src/common.h src/constantnumbers.h src/matlabfunctions.h
```

Now if we modify `src/common.h`, all these three file will be recompiled; if we only modify `d4c.h`, then only D4C will be recompiled.

The following is a pattern match for any `.o` files, unless otherwise specified:
```makefile
$(OUT_DIR)/%.o : src/%.cpp
	mkdir -p build
	$(CC) $(CFLAGS) -o $(OUT_DIR)/$*.o -c src/$*.cpp
```
Where the second line creates a `build` directory if it doesn't exist. The third line replaces a very general command by specific tools, files and locations.

Just google it and you can find a bunch of tutorials on makefile.
One great thing about version control is that you can test out new ideas by creating new branches, without modifying the codes in stable version/master branch. Another great thing is when you did something wrong but only realized it several weeks later, you can use `git revert` to undo the changes to an arbitrary commit in the past. To fully harness these advantages, it would be helpful to be more specific on commit messages (e.g. "Fix overflow bug in xxx.c" rather than "Bug fix").

**Comment by mmorise** [comment]
Thank you your comments. I'll marge your request tomorrow after checking.

If you have time, please teach me about Makefile.
I think Makefile.linux under platform can work by revising the path information.
In top of the project, src/constantnumbers.h is correct. On the other hand, 
in platform/linux, I think ../../src/constantnumbers.h is also correct.

I have no idea whether the files for building the executable file should be put under each platform.
Or should it be put under the top accordance with your idea?
(Maybe I think you recommend me to put Makefile under the top.)
Since I'm not used to using Makefile, I will follow the traditional style in Makefile.

**Comment by Sleepwalking** [comment]
> I think Makefile.linux under platform can work by revising the path information.
In top of the project, src/constantnumbers.h is correct. On the other hand,
in platform/linux, I think ../../src/constantnumbers.h is also correct.

Yes.

> I have no idea whether the files for building the executable file should be put under each platform.

Many open source projects put their makefiles under the top; some others put them under `src/`.
When you have multiple build systems (e.g. makefile, Visual Studio, cmake...), it's common to put all of them under the top, as long as they don't interfere each other.
But it's also ok to have a `platform` directory. In such case, you should create a capitalized `INSTALL` file under the top, where you write the instructions for how to build.

Actually makefile is cross-platform. In Windows you can use it under MSYS or CYGWIN with minor or no modification.

There are [plenty of tutorials](https://www.google.com.hk/?gws_rd=ssl#newwindow=1&safe=strict&q=makefile+tutorial) on makefile. Sorry that I can't tell which one is the best, but they are definitely enough to meet your needs; many are quite concise that you can get used to it in a day.

**Pull request merged**
