### PR TITLE
Refactoring the code to be more flexible

### PR DESCRIPTION
**Pull request by seblemaguer**
Hello,

I refactored a little bit the code to have a clearer organized repository and I have added an analysis and synthesis program. For now I haven't adapted wavesynthesis2 and 3. Just the first method is achieved but I plan to do it soon

### CODE REVIEW

**Comment by mmorise** [comment]
Thank you for your requests.
Since I'm in a business trip, I don't test the requested programs.

I think that the concept of requests sounds good.
In particular, it is nice to add independent tests in analysis and synthesis with test.sh.
On the other hand, I think the test programs should be separated from WORLD-core program.
In this case, analysis.cpp, audioio.cpp/.h, and synthesis.cpp should be in the "test" directory.

Moreover, I think that cmake is excessive because WORLD does not depend on the OS, and a simple Makefile is enough for WORLD.
The users must install cmake, and I'd like to avoid such an extra step.
If my concern is misunderstanding, please point it.

**Comment by seblemaguer** [comment]
Hello,

do not worry for the checking take your time :) 

for the the first point, I think analysis and synthesis and audioio are not testing part. I understand the fact they are not as flexible as they should be right now but I suspect people who wants to use a vocoder wants to have binaries to extract coefficients from a sound file and then generate the sounds from the coefficient. I'm thinking in a first place at a TTS context. That's why I put all the library core source code into src/world and then the binary code into src/. You still have a clear separation between the core and the rest.

Considering cmake, I understand your concern. On my side I find it really practical for : 
  - system/local installation process
  - version management
  - project management (for example you can remove your visual studio project directory and directly using cmake to generate it.
I don't know how difficult it is to install cmake on windows but on linux it is trivial. Generally someone who wants to compile a code won't mind installing cmake. People who are just going to use the library should have it in a package form.
However, if you don't like it we can go back to the makefile :)

**Comment by m-toman** [comment]
Hi all,

does CMake override the existing makefiles when doing an out of tree build?
(`mkdir build; cd build; cmake ..; make`)
Then you could easily retain both.

Personally I also like CMake very much, but on Windows I also prefer not to create the Visual Studio projects with it - everytime you change something: close VS, change CMakeFiles, recreate VS project. Also, often the created VS project files are not exactly as you would like them to be.

**Comment by seblemaguer** [comment]
@m-toman yes it does. 

considering the created project, I didn't get what is happening can you explain it a little bit more in details ?

**Comment by mmorise** [comment]
Thank you for comments > all.

I have never used cmake, and my development environment is VS2015.
Since I have no LINUX PC, the test is usually carried out in Cygwin in Windows.
So, I'm reluctant to use cmake.

**Comment by m-toman** [comment]
@seblemaguer

In my experience, the workflow when working with visual studio and cmake is:
Everytime you would change any project setting (say, add a file, change a compiler flag, set a preprocessor macro etc.) you instead close visual studio,  modify the cmake files, create a new visual studio project, open it again.

Moreover, it's quite tricky to get some settings right with the cmake files. For example, setting up an ActiveX project for SAPI.

Other things are probably possible but didn't look them up now, like project dependencies.

On the other hand, many open source projects have pretty messed up VS projects, e.g. regarding to the settings for the different architectures and debug/release. So at least you can create a clean state :).

**Comment by mmorise** [comment]
Thank you for your proposal.

Since I can't maintain several parts (e.g. cmake and Travis CI), I think that it's preferable to release a series of modifications as your own effort.
My repository consists of the minimum package for developers, and I recommend that your expansion is maintained by your repository.
I will willingly add the link to your repository from here.

**Comment by seblemaguer** [comment]
ok I understand. I will refactor that in order to have the makefile with the program. We can think later for the cmake/travis part

**Comment by seblemaguer** [comment]
is it ok like that ?

**Comment by mmorise** [comment]
I was wondering if you could move the files in the directory "src" to an independent directory.
For example,
/src/(world-core files only)
/tools/audioio.cpp, audioio.h
/examples/analysis.cpp, synthesis.cpp readme.md (I will add the guide)
/test/ctest.c, test.cpp, vaiueo2d.wav

I would like to separate functions such as file input/output from the programs in WORLD-Core.
The users would be able to use these tools and examples.
On the other hand, they can also use functions implemented by themselves.

**Comment by seblemaguer** [comment]
hello,

sorry for the delay. Is it ok like that ?

**Comment by mmorise** [comment]
I confirmed your requests. If possible, I'd like to add a module for outputting the header information (e.g. sampling frequency and frame period). I will fix other minor errors (e.g. line 95 in makefile) after merging. To clearly show your effort, I will add the header in analysis.cpp/synthesis.cpp.

**Comment by mmorise** [comment]
If you allow these conditions, I will merge your request and start the coding.

**Comment by seblemaguer** [comment]
sure I agree :)

**Pull request merged**
